---
- name: Register member clusters with Karmada
  when: inventory_hostname in groups['workers']
  ansible.builtin.command: >
    kubectl
    karmada
    join
    {{ cluster_name }}
    --kubeconfig=/root/.kube/config
    --cluster-context={{ cluster_name }}
    --karmada-context=karmada-apiserver
  environment:
    KUBECONFIG: "/root/.kube/config"
  register: join_result
  delegate_to: "{{ groups['control'][0] }}"
  failed_when:
    - join_result.rc != 0
    - "'the same cluster has been registered' not in join_result.stderr"
  changed_when:
    - join_result.rc == 0
    - "'cluster is joined successfully' in join_result.stdout"
  vars:
    cluster_name: "{{ inventory_hostname }}"

- name: Verify that member clusters are registered
  ansible.builtin.command: >
    kubectl --context karmada-apiserver get clusters -A
  environment:
    KUBECONFIG: "/root/.kube/config"
  delegate_to: "{{ groups['control'][0] }}"
  register: clusters_result
  changed_when: false

- name: Display registered clusters
  ansible.builtin.debug:
    var: clusters_result.stdout_lines
