---
- name: Karmada host prereqs
  ansible.builtin.include_tasks: install_prereqs.yml
  when: inventory_hostname in groups['control']
  tags: karmada-prereqs

- name: Karmada control plane setup
  ansible.builtin.include_tasks: setup_karmada.yml
  when: inventory_hostname in groups['control']
  tags: karmada-install

- name: Setup kubectl
  ansible.builtin.include_tasks: setup_kubectl.yml
  when: inventory_hostname in groups['control']
  tags: karmada-kubectl

- name: Setup GPU operator deployments
  ansible.builtin.include_tasks: setup_gpu_operator.yml
  when: inventory_hostname in groups['workers']
  tags: karmada-gpu-operator

- name: Join member clusters
  ansible.builtin.include_tasks: join_clusters.yml
  when: inventory_hostname in groups['workers']
  tags: karmada-join-cluster

- name: Karmada monitoring setup
  ansible.builtin.include_tasks: setup_monitoring.yml
  when: inventory_hostname in groups['control']
  tags: monitoring
