---
- name: Add NVIDIA Helm repository
  kubernetes.core.helm_repository:
    name: nvidia
    repo_url: https://helm.ngc.nvidia.com/nvidia

- name: Install GPU Operator
  kubernetes.core.helm:
    name: gpu-operator
    chart_ref: nvidia/gpu-operator
    release_namespace: gpu-operator
    create_namespace: true
    state: present
    force: true
    kubeconfig: "{{ karmada_kubeconfig_path | default(omit) }}"
    context: karmada-apiserver
    values:
      driver:
        enabled: false
      toolkit:
        enabled: false
      operator:
        upgradeCRD: false

- name: Copy propagation policy
  ansible.builtin.copy:
    src: gpu-operator.pp.yaml
    dest: /tmp/gpu-operator.pp.yaml
    mode: "0644"

- name: Create GPU operator propagation policies
  kubernetes.core.k8s:
    src: /tmp/gpu-operator.pp.yaml
    state: present
    namespace: gpu-operator
    context: karmada-apiserver
