---
# inventory.yml
all:
  children:
    control:
      hosts:
        chutes-miner-control0:
          ansible_host: 10.0.0.1
    workers:
      hosts:
        chutes-miner-gpu0:
          ansible_host: 10.0.0.2
        chutes-miner-gpu1:
          ansible_host: 10.0.0.3
  vars:
    ansible_ssh_private_key_file: ~/.ssh/your_key.pem
