{{- define "redis.url" -}}
redis://:$(REDIS_PASSWORD)@chutes-miner-redis:6379
{{- end }}

{{- define "postgresql.url" -}}
postgresql+asyncpg://{{ .Values.postgres.database.user }}:$(POSTGRES_PASSWORD)@chutes-miner-postgres:5432/{{ .Values.postgres.database.name }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chutes-miner-api
  labels:
    {{- include "minerApi.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "minerApi.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minerApi.labels" . | nindent 8 }}
    spec:
      {{- with .Values.minerApi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minerApi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minerApi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.minerApi.image }}"
          imagePullPolicy: {{ .Values.minerApi.imagePullPolicy }}
          command: ["poetry", "run", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "{{ .Values.minerApi.service.targetPort }}"]
          env:
            - name: MINER_SS58
              valueFrom:
                secretKeyRef:
                  name: miner-credentials
                  key: ss58
            - name: MINER_SEED
              valueFrom:
                secretKeyRef:
                  name: miner-credentials
                  key: seed
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chutes-miner-redis-secret
                  key: {{ .Values.redis.password.passwordKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chutes-miner-postgres-secret
                  key: {{ .Values.postgres.database.passwordKey }}
            - name: POSTGRESQL
              value: {{ include "postgresql.url" . }}
            - name: REDIS_URL
              value: {{ include "redis.url" . }}
            - name: SQUID_PORT
              value: "{{ .Values.squid.service.port }}"
            - name: VALIDATORS
              value: {{ .Values.validators | toJson | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.minerApi.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.minerApi.resources | nindent 12 }}
