{{- define "redis.url" -}}
redis://:$(REDIS_PASSWORD)@chutes-miner-redis:6379
{{- end }}

{{- define "postgresql.url" -}}
postgresql+asyncpg://{{ .Values.postgres.database.user }}:$(POSTGRES_PASSWORD)@chutes-miner-postgres:5432/{{ .Values.postgres.database.name }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chutes-miner-api
  labels:
    {{- include "minerApi.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "minerApi.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minerApi.labels" . | nindent 8 }}
    spec:
      {{- with .Values.minerApi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minerApi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minerApi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.minerApi.image }}"
          imagePullPolicy: {{ .Values.minerApi.imagePullPolicy }}
          env:
            - name: MINER_HOTKEY_SS58
              valueFrom:
                secretKeyRef:
                  name: miner-credentials
                  key: ss58
            - name: MINER_SEED
              valueFrom:
                secretKeyRef:
                  name: miner-credentials
                  key: seed
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.redis.password.existingSecret }}{{ .Values.redis.password.existingSecret }}{{ else }}chutes-miner-redis-secret{{ end }}
                  key: {{ .Values.redis.password.existingSecretKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.postgres.database.existingSecret }}{{ .Values.postgres.database.existingSecret }}{{ else }}chutes-miner-postgres-credentials{{ end }}
                  key: {{ .Values.postgres.database.passwordKey }}
            - name: DATABASE_URL
              value: {{ include "postgresql.url" . }}
            - name: REDIS_URL
              value: {{ include "redis.url" . }}
            - name: VALIDATORS
              value: {{ .Values.validators | toJson | quote }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.minerApi.resources | nindent 12 }}
