apiVersion: v1
kind: Service
metadata:
  name: chutes-porter
  labels:
    {{- include "porter.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.porter.service.nodePort }}
      port: {{ .Values.porter.service.port }}
      targetPort: {{ .Values.porter.service.targetPort }}
      name: porter
  selector:
    {{- include "porter.labels" . | nindent 4 }}
