apiVersion: apps/v1
kind: Deployment
metadata:
  name: chutes-miner-redis
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redis.labels" . | nindent 8 }}
    spec:
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          imagePullPolicy: {{ .Values.redis.imagePullPolicy }}
          args:
            - redis-server
            - --requirepass
            - $(REDIS_PASSWORD)
            {{- range .Values.redis.config.customArgs }}
            - {{ . }}
            {{- end }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.redis.password.existingSecret }}{{ .Values.redis.password.existingSecret }}{{ else }}chutes-miner-redis-secret{{ end }}
                  key: {{ .Values.redis.password.existingSecretKey }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          {{- end }}
      {{- if .Values.redis.persistence.enabled }}
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: chutes-miner-redis-data
      {{- end }}
