apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.registry.replicaCount }}
  selector:
    matchLabels:
      {{- include "registry.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "registry.labels" . | nindent 8 }}
    spec:
      {{- with .Values.registry.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: registry
          image: "{{ .Values.registry.image }}"
          imagePullPolicy: {{ .Values.registry.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.registry.resources | nindent 12 }}
          volumeMounts:
            - name: registry-nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: registry-nginx-config
          configMap:
            name: registry-nginx-config
