{{- $root := . -}}
{{- range .Values.validators.supported }}
apiVersion: v1
kind: Service
metadata:
  name: registry-{{ .hotkey | lower }}
  labels:
    {{- include "registry.labels" $root | nindent 4 }}
spec:
  type: {{ $root.Values.registry.service.type }}
  ports:
    - port: {{ $root.Values.registry.service.port }}
      targetPort: {{ $root.Values.registry.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "registry.labels" $root | nindent 4 }}
---
{{- end }}
