apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chutes-miner-squid-network-policy
  labels:
    {{- include "squid.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "squid.labels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              proxy-access: "true"
      ports:
        - protocol: TCP
          port: 3128
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 21
