apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-config
data:
  squid.conf: |
    http_port {{ .Values.squid.service.port }}
    visible_hostname squid
    cache deny all
    cache_mem 0 MB
    cache_dir null /tmp

    acl allowed_sites dstdomain "/etc/squid/allowed-sites.txt"
    acl SSL_ports port 443
    acl CONNECT method CONNECT
    http_access deny CONNECT !SSL_ports
    http_access allow allowed_sites
    http_access deny all

  allowed-sites.txt: |
    # Chutes.
    .chutes.ai
    .chutes.dev

    # Hugging Face domains
    .huggingface.co
    .huggingface.net
    .hf.space
    .hf.co

    # Model and Dataset Repositories
    .civitai.com
    .modelscope.cn
    .weights.ggmlv3.model
    .weights.gguf.model
    .pytorch.org
    .torchvision.org
    .tensorflow.org
    .tfhub.dev
    .nvidia.github.io
    .ngc.nvidia.com
    .developer.nvidia.com
    .files.pythonhosted.org
    .github.com
    .githubusercontent.com
    .objects.githubusercontent.com
    .raw.githubusercontent.com
    .gitlab.com
    .anaconda.org
    .anaconda.com
    .pip.pypa.io
    .pypi.org
    .pypi.python.org

    # Common CDNs
    .cloudfront.net
    .fastly.net
    .akamai.net
    .cloudflare.com
    .jsdelivr.net
    .unpkg.com
    .bunny.net
    .cdn.jsdelivr.net
    .cdnjs.cloudflare.com
    .googleusercontent.com
    .storage.googleapis.com

    # Cloud Storage
    .s3.amazonaws.com
    .s3-*.amazonaws.com
    .s3.*.amazonaws.com
    .storage.googleapis.com
    .azureedge.net
    .blob.core.windows.net

    # AI Platform Services
    .openai.com
    .api.openai.com
    .anthropic.com
    .api.anthropic.com
    .cohere.ai
    .api.cohere.ai
    .stability.ai
    .api.stability.ai
    .wandb.ai
    .mlflow.org
    .tensorboard.dev
    .neptune.ai

    # Academic and Research
    .arxiv.org
    .paperswithcode.com
    .research.google.com
    .research.facebook.com
    .microsoft.com
