apiVersion: v1
kind: ConfigMap
metadata:
  name: chutes-miner-squid-config
  labels:
    {{- include "squid.labels" . | nindent 4 }}
data:
  squid.conf: |
    http_port 3128
    workers {{ .Values.squid.config.workerThreads }}
    pipeline_prefetch {{ .Values.squid.config.pipelineRequests }}
    read_ahead_gap {{ .Values.squid.config.readAheadSize }}
    maximum_object_size {{ .Values.squid.config.maxRequestSize }}
    cache_mem {{ .Values.squid.config.cacheSize }} MB
    cache_dir ufs /var/spool/squid {{ int .Values.squid.config.diskCache.size }} {{ .Values.squid.config.diskCache.level1 }} {{ .Values.squid.config.diskCache.level2 }}
    range_offset_limit none
    offline_mode off
    reload_into_ims on
    memory_cache_mode always
    dns_nameservers 1.1.1.1,1.0.0.1,8.8.8.8 8.8.4.4
    logformat combined %>a %ui %un [%tl] "%rm %ru HTTP/%rv" %Hs %<st "%{Referer}>h" "%{User-Agent}>h" %Ss:%Sh
    access_log /var/log/squid/access.log combined
    cache_log /var/log/squid/cache.log
    
    acl SSL_ports port 443
    acl Safe_ports port 80
    acl Safe_ports port 443
    acl CONNECT method CONNECT
    {{- range .Values.squid.config.allowedNetworks }}
    acl internal_networks src {{ . }}
    {{- end }}
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports
    http_access allow internal_networks
    http_access deny all

    {{- range .Values.squid.config.refreshPatterns }}
    refresh_pattern {{ .pattern }} {{ .min }} {{ .percent }}% {{ .max }} ignore-reload
    {{- end }}
    refresh_pattern -i \.huggingface\. 10080 100% 43200 ignore-reload
    refresh_pattern -i \.amazonaws\.com 10080 100% 43200 ignore-reload
    refresh_pattern . 0 20% 4320
    request_body_max_size 1048576
    reply_body_max_size 1048576
    cache_replacement_policy heap LFUDA
    memory_replacement_policy heap GDSF
