apiVersion: v1
kind: Service
metadata:
  name: squid
  labels:
    {{- include "squid.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  internalTrafficPolicy: Local
  ports:
    - port: {{ .Values.squid.service.port }}
      targetPort: {{ .Values.squid.service.port }}
      protocol: TCP
      name: squid
  selector:
    {{- include "squid.labels" . | nindent 4 }}
