apiVersion: apps/v1
kind: Deployment
metadata:
  name: chutes-miner-squid
  labels:
    {{- include "squid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.squid.replicaCount }}
  selector:
    matchLabels:
      {{- include "squid.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "squid.labels" . | nindent 8 }}
    spec:
      {{- with .Values.squid.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.squid.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.squid.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: squid
          image: "{{ .Values.squid.image }}"
          imagePullPolicy: {{ .Values.squid.imagePullPolicy }}
          ports:
            - name: proxy
              containerPort: 3128
              protocol: TCP
          resources:
            {{- toYaml .Values.squid.resources | nindent 12 }}
          volumeMounts:
            - name: squid-config
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
            - name: cache-dir
              mountPath: /var/spool/squid
          readinessProbe:
            tcpSocket:
              port: 3128
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3128
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: squid-config
          configMap:
            name: chutes-miner-squid-config
        - name: cache-dir
          {{- if .Values.squid.persistence.enabled }}
          persistentVolumeClaim:
            claimName: chutes-miner-squid-cache
          {{- else }}
          emptyDir: {}
          {{- end }}
