apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: chutes-miner-squid
  labels:
    {{- include "squid.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "squid.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "squid.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- toYaml .Values.squid.nodeSelector | nindent 8 }}
      containers:
        - name: squid
          image: "{{ .Values.squid.image }}"
          imagePullPolicy: {{ .Values.squid.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 3128
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
            - name: config
              mountPath: /etc/squid/allowed-sites.txt
              subPath: allowed-sites.txt
            - name: cache
              mountPath: /var/cache/squid
          resources:
            {{- toYaml .Values.squid.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: chutes-miner-squid-config
        - name: cache
          emptyDir: {}
