apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chutes
subjects:
- kind: ServiceAccount
  name: chutes
  namespace: chutes
roleRef:
  kind: ClusterRole
  name: chutes
  apiGroup: rbac.authorization.k8s.io
