apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: squid-np
  labels:
    {{- include "squid.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "squid.labels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              squid-access: "true"
      ports:
        - protocol: TCP
          port: 3128
