createPasswords: false  # XXX only ever set to true one time (first time)!!!

cache:
  maxAgeDays: 7
  maxSizeGB: 500

validators:
  defaultRegistry: registry.chutes.ai
  defaultApi: https://api.chutes.ai
  supported:
    - hotkey: 5Dt7HZ7Zpw4DppPxFM7Ke3Cm7sDAWhsZXmM5ZAmE7dSVJbcQ
      registry: registry.chutes.ai
      api: https://api.chutes.ai
      socket: wss://ws.chutes.ai

porter:
  enabled: true
  service:
    nodePort: 31000
    port: 8000
    targetPort: 8000
  real_host: 1.2.3.4
  real_port: 32000
  image: parachutes/porter:latest
  imagePullPolicy: Always
  resources:
    requests:
      cpu: "250m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "128Mi"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: chutes-porter
            operator: In
            values:
              - "true"

minerApi:
  image: parachutes/miner:latest
  imagePullPolicy: Always
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  service:
    type: NodePort
    nodePort: 32000
    port: 8000
    targetPort: 8000
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: NotIn
            values: ["true"]
          - key: chutes-porter
            operator: NotIn
            values:
              - "true"
  tolerations: []


squid:
  image: ubuntu/squid:5.2-22.04_beta
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  service:
    port: 3128
  nodeSelector:
    nvidia.com/gpu.present: "true"

gepetto:
  image: parachutes/miner:latest
  imagePullPolicy: Always
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: NotIn
            values: ["true"]
          - key: chutes-porter
            operator: NotIn
            values:
              - "true"
  tolerations: []

postgres:
  image: postgres:16
  imagePullPolicy: IfNotPresent
  persistence:
    enabled: true
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  database:
    name: chutes
    user: chutes
    passwordKey: "postgres-password"
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - chutes-miner-cpu-0
  tolerations: []

redis:
  image: redis:7
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: NotIn
            values: ["true"]
          - key: chutes-porter
            operator: NotIn
            values:
              - "true"
  tolerations: []
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  service:
    type: ClusterIP
    port: 6379
  password:
    passwordKey: "redis-password"
  config:
    customArgs: []

registry:
  image: nginx:1.27
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
    # BE SURE THIS MATCHES registry_port IN ANSIBLE!
    nodePort: 30500
  nodeSelector:
    nvidia.com/gpu.present: "true"
  config:
    workerProcesses: 1
    workerConnections: 1024
    keepaliveTimeout: 65
    clientMaxBodySize: "0"
    validators:
      allowedHosts:
        - "registry.chutes.ai"
      defaultUpstream: "registry.chutes.ai"
