{{ if .Values.multiCluster }}
# PropagationPolicy for GPU Operator Namespace
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: chutes-namespace-policy
spec:
  priority: 100
  resourceSelectors:
    - apiVersion: v1
      kind: Namespace
      name: chutes
  placement:
    clusterAffinity:
      clusterNames: []
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: chutes-resource-policy
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      namespace: chutes
      name: chutes-cache-cleaner
    - apiVersion: v1
      kind: ConfigMap
      namespace: chutes
      labelSelector:
        matchLabels:
          chutes/code: "true"
    - apiVersion: batch/v1
      kind: CronJob
      namespace: chutes
      name: failed-chute-cleanup
    - apiVersion: v1
      kind: Secret
      namespace: chutes
      name: miner-credentials
    - apiVersion: v1
      kind: Secret
      namespace: chutes
      name: regcred
    - apiVersion: v1
      kind: ServiceAccount
      namespace: chutes
      name: chutes
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      namespace: chutes
      name: chutes
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      namespace: chutes
      name: chutes
  placement:
    clusterAffinity:
      clusterNames: []
{{- end }}
