- name: Enable community plugins
  hosts: all
  become: yes
  tasks:
    - name: Enable community plugins
      shell: |
        microk8s enable community || (sleep 10 && microk8s enable community) || true
      ignore_errors: yes
      when: is_primary | bool

- name: Install NVidia GPU Operator
  hosts: all
  become: yes
  tasks:
    - name: Install GPU Operator
      shell: |
        microk8s helm repo add nvidia https://helm.ngc.nvidia.com/nvidia || true
        microk8s helm repo update
        microk8s helm install gpu-operator nvidia/gpu-operator \
          --namespace gpu-operator \
          --create-namespace \
          --set nodeSelector.kubernetes.io/gpu="true" \
          --set driver.enabled=true \
          --set toolkit.enabled=true \
          --set devicePlugin.enabled=true \
          --set operator.runtimeClass="nvidia-container-runtime" \
          --set operator.defaultRuntime=containerd \
          --insecure-skip-tls-verify \
          --kube-insecure-skip-tls-verify
      when: is_primary | bool

- name: Install Prometheus
  hosts: all
  become: yes
  tasks:
    - name: Install Prometheus
      shell: |
        microk8s helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
        microk8s helm repo update
        microk8s helm install prometheus prometheus-community/prometheus \
          --namespace chutes \
          --create-namespace \
          --set server.persistentVolume.enabled=false \
          --set alertmanager.persistentVolume.enabled=false \
          --set prometheus-pushgateway.persistentVolume.enabled=false \
          --set prometheus-server.persistentVolume.enabled=false \
          --set alertmanager.persistence.enabled=false \
          --set server.nodeSelector."kubernetes\.io/hostname"={{ inventory_hostname }} \
          --set alertmanager.nodeSelector."kubernetes\.io/hostname"={{ inventory_hostname }} \
          --set pushgateway.nodeSelector."kubernetes\.io/hostname"={{ inventory_hostname }} \
          --set kubeStateMetrics.nodeSelector."kubernetes\.io/hostname"={{ inventory_hostname }} \
          --insecure-skip-tls-verify --kube-insecure-skip-tls-verify
      when: is_primary | bool
