- name: Enable plugins
  hosts: all
  become: yes
  tasks:
    - name: Check if plugins are enabled
      shell: microk8s status | grep -E "dns|hostpath-storage|cilium|acting as a node in a cluster"
      register: plugins_check
      changed_when: false
      ignore_errors: yes
    - name: Enable MicroK8s plugins
      shell: |
        microk8s enable community || (sleep 10 && microk8s enable community) || true
        microk8s enable hostpath-storage ||  (sleep 10 && microk8s enable hostpath-storage) || true
        microk8s enable cilium || (sleep 10 && microk8s enable cilium) || true
      ignore_errors: yes
      when: plugins_check.failed and is_primary | bool
      register: plugins_enabled

- name: Install NVidia GPU Operator
  hosts: all
  become: yes
  tasks:
    - name: Install GPU Operator
      shell: |
        microk8s helm repo add nvidia https://helm.ngc.nvidia.com/nvidia || true
        microk8s helm repo update
        microk8s helm install gpu-operator nvidia/gpu-operator \
          --namespace gpu-operator \
          --create-namespace \
          --set nodeSelector.kubernetes.io/gpu="true" \
          --set driver.enabled=true \
          --set toolkit.enabled=true \
          --set devicePlugin.enabled=true \
          --set operator.runtimeClass="nvidia-container-runtime" \
          --set operator.defaultRuntime=containerd \
          --insecure-skip-tls-verify \
          --kube-insecure-skip-tls-verify
      when: is_primary | bool

- name: Install Prometheus
  hosts: all
  become: yes
  tasks:
    - name: Install Prometheus
      shell: |
        microk8s helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
        microk8s helm repo update
        microk8s helm install prometheus prometheus-community/prometheus --namespace chutes --create-namespace --insecure-skip-tls-verify --kube-insecure-skip-tls-verify
      when: is_primary | bool
